INSERT INTO TB_ROLE (ID,NAME) VALUES (1L,'Backend Developer Java Jr');
INSERT INTO TB_ROLE (ID,NAME) VALUES (2L,'Backend Developer C#');
INSERT INTO TB_ROLE (ID,NAME) VALUES (3L,'Fullstack Developer');

INSERT INTO TB_STATECODE (ID,initials) VALUES (1L,'AC');
INSERT INTO TB_STATECODE (ID,initials) VALUES (2L,'AL');
INSERT INTO TB_STATECODE (ID,initials) VALUES (3L,'AP');
INSERT INTO TB_STATECODE (ID,initials) VALUES (4L,'AM');
INSERT INTO TB_STATECODE (ID,initials) VALUES (5L,'BA');
INSERT INTO TB_STATECODE (ID,initials) VALUES (6L,'CE');
INSERT INTO TB_STATECODE (ID,initials) VALUES (7L,'DF');
INSERT INTO TB_STATECODE (ID,initials) VALUES (8L,'ES');
INSERT INTO TB_STATECODE (ID,initials) VALUES (9L,'GO');
INSERT INTO TB_STATECODE (ID,initials) VALUES (10L,'MA');
INSERT INTO TB_STATECODE (ID,initials) VALUES (11L,'MT');
INSERT INTO TB_STATECODE (ID,initials) VALUES (12L,'MS');
INSERT INTO TB_STATECODE (ID,initials) VALUES (13L,'MG');

INSERT INTO TB_CANDIDATE (USERNAME,DOC,EMAIL,PORTFOLIO, ROLE_ID,STATE_CODE_ID) VALUES ('Michele','9833839938393','michele@gmail.com','https://portfolioexample.com.br',1L,1L);
INSERT INTO TB_CANDIDATE (USERNAME,DOC,EMAIL,PORTFOLIO, ROLE_ID,STATE_CODE_ID) VALUES ('Luiz Carlos','88383838383','lewiscarlos@gmail.com','https://portfolioexample.com.br',2L,13L);
INSERT INTO TB_CANDIDATE (USERNAME,DOC,EMAIL,PORTFOLIO, ROLE_ID,STATE_CODE_ID) VALUES ('Nelson Gustavo','29393339393','nelson.golcalvez@gmail.com','https://portfolioexample.com.br',3L,7L);
