INSERT INTO TB_ROLE (ID,NAME) VALUES (1,'Backend Developer Java Jr');
INSERT INTO TB_ROLE (ID,NAME) VALUES (2,'Backend Developer C#');
INSERT INTO TB_ROLE (ID,NAME) VALUES (3,'Fullstack Developer');

INSERT INTO TB_STATECODE (initials) VALUES ('AC');
INSERT INTO TB_STATECODE (initials) VALUES ('AL');
INSERT INTO TB_STATECODE (initials) VALUES ('AP');
INSERT INTO TB_STATECODE (initials) VALUES ('AM');
INSERT INTO TB_STATECODE (initials) VALUES ('BA');
INSERT INTO TB_STATECODE (initials) VALUES ('CE');
INSERT INTO TB_STATECODE (initials) VALUES ('DF');
INSERT INTO TB_STATECODE (initials) VALUES ('ES');
INSERT INTO TB_STATECODE (initials) VALUES ('GO');
INSERT INTO TB_STATECODE (initials) VALUES ('MA');
INSERT INTO TB_STATECODE (initials) VALUES ('MT');
INSERT INTO TB_STATECODE (initials) VALUES ('MS');
INSERT INTO TB_STATECODE (initials) VALUES ('MG');

INSERT INTO TB_CANDIDATE (ID,USERNAME,DOC,EMAIL,PORTFOLIO, ROLE_ID,STATE_CODE_ID) VALUES (1,'Michele','9833839938393','michele@gmail.com','https://portfolioexample.com.br',1,1);
INSERT INTO TB_CANDIDATE (ID,USERNAME,DOC,EMAIL,PORTFOLIO, ROLE_ID,STATE_CODE_ID) VALUES (2,'Luiz Carlos','88383838383','lewiscarlos@gmail.com','https://portfolioexample.com.br',2,13);
INSERT INTO TB_CANDIDATE (ID,USERNAME,DOC,EMAIL,PORTFOLIO, ROLE_ID,STATE_CODE_ID) VALUES (3,'Nelson Gustavo','29393339393','nelson.golcalvez@gmail.com','https://portfolioexample.com.br',3,7);
